#!/Users/Likianta/Desktop/programs/python/3.11/bin/python3
import sys
import subprocess as sp

ROOT = '$DEPSLAND_DIR'
APPID = '$APPID'
VERSION = '$VERSION'

sys.path.insert(0, f'{ROOT}')
sys.path.insert(0, f'{ROOT}/apps/.venv/{APPID}')
sys.path.insert(0, f'{ROOT}/apps/{APPID}/{VERSION}')

sp.run(
    (sys.executable, '-m', 'depsland', 'run', APPID, '--:version', VERSION),
    stdout=sp.PIPE, stderr=sp.PIPE,
)
