[tool.poetry]
name = "depsland"
version = "0.6.0a0"
description = ""
license = "MIT"
authors = ["Likianta <likianta@foxmail.com>"]
homepage = "https://github.com/likianta/depsland"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.10"
argsense = "^0.5.2"
conflore = "^0.2.0"
lk-logger = "^5.4.8"
lk-utils = "^2.5.4"
oss2 = "*"
# pyside6 = "*"
pyyaml = "*"
qmlease = "^3.0.3"
rich = "*"
semver = "^3.0.0dev4"

[tool.poetry.extras]

[tool.poetry.scripts]
depsland = 'depsland.__main__:_run_cli'

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
