[tool.poetry]
name = "depsland"
version = "0.6.1"
description = ""
license = "MIT"
authors = ["Likianta <likianta@foxmail.com>"]
homepage = "https://github.com/likianta/depsland"

# po export -o requirements.lock --without-hashes
# python/python.exe -m pip install -r requirements.lock --no-deps \
#   --no-warn-script-location --disable-pip-version-check

[tool.poetry.dependencies]
python = "^3.10"
argsense = "^0.5.3"
conflore = "^0.2.0"
lk-logger = "^5.6.3"
lk-utils = "^2.7.0"
oss2 = "*"
# pyside6 = "*"
pyyaml = "*"
qmlease = "^3.0.3"
# qmlease = { url = "http://likianta.pro:2006/qmlease/qmlease-3.1.0a16-py3-none-any.whl" }
rich = "*"
semver = "^3.0.0dev4"
windows-toasts = { version = "*", platform = "win32" }

[tool.poetry.scripts]
depsland = 'depsland.__main__:_run_cli'

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
priority = "default"

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
