[tool.poetry]
name = "depsland"
version = "0.1.0a30"
description = ""
authors = ["Likianta <likianta@foxmail.com>"]
license = "MIT"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.10"
argsense = "^0.5.0a0"
lk-logger = "^5.4.6"
lk-utils = "~2.5.0b10"
oss2 = "*"
pyyaml = "*"
rich = "*"
semver = "3.0.0dev3"
wheel = "*"

[tool.poetry.extras]

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
