[tool.poetry]
name = "depsland"
version = "0.8.0b7"
description = "User oriented dependency management and application distribution tool."
license = "MIT"
authors = ["Likianta <likianta@foxmail.com>"]
homepage = "https://github.com/likianta/depsland"

[tool.poetry.dependencies]
python = "^3.8"
argsense = "^0.5.8"
# argsense = { version = "^0.5.7b0", source = "likianta-host" }
conflore = "^0.2.0"
# dash = "*"
# dash-antd = "*"
# lk-logger = "^5.7.5"
lk-logger = { version = "^5.7.6b1", source = "likianta-host" }
# lk-utils = "^2.10.1"
lk-utils = { version = "^2.10.7a3", source = "likianta-host" }
oss2 = "^2.18.3"  # DELETE
pip = "^24.0.0"
pipgrip = "^0.10.13"
poetry = "^1.8.3"
psutil = "^6.0.0"
# pyapp-window = "1.0.0"
pyapp-window = { version = "^2.0.0a9", source = "likianta-host" }
# pyapp-window = { version = "1.0.0", source = "likianta-host" }
# pyside6 = [
#     { version = ">=6.4.3,<6.5.0", python = ">=3.8,<3.12" },
#     { version = "^6.7.1", python = ">=3.12,<3.13" },
# ]
pyyaml = "^6.0.0"
# qmlease = "^3.0.4"
rich = "^13.7.0"
semver = "^3.0.2"
streamlit = { version = "^1.36.0", python = "!=3.9.7" }
streamlit-extras = "*"
# streamlit-scrollable-textbox = "*"
# toml = { version = "*", python = "<3.11" }
toml = "*"
# typing-extensions = { version = "*", python = "<3.11" }
windows-toasts = { version = "^1.0.0", platform = "win32" }

# --- fix indirect dependencies' verspecs ---
numpy = { version = "^1.26.0", python = ">=3.9" }  # <- streamlit
pandas = { version = "^2.2.2", python = ">=3.9" }  # <- streamlit

[tool.poetry.group.dev.dependencies]
icnsutil = "*"  # <- sidework/image_converter.py
ipython = { version = "^8.22.0", python = ">=3.10,<4.0" }
# modulegraph = "^0.19.6"
nuitka = "^2.3.11"
pillow = "*"  # <- sidework/image_converter.py
pyside6 = { version = ">=6.6.0,<6.7.0", python = ">=3.10,<3.13" }  # <- demo/hello-world-gui
pysimplegui = "*"  # <- demo/hello-world-tkinter
# qmlease = "^3.0.4"  # <- demo/hello-world-gui
qmlease = { version = ">=3.0.5a4,<3.1.0", source = "likianta-host" }

[tool.poetry.scripts]
depsland = 'depsland.__main__:_run_cli'

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "likianta-host"
url = "http://likianta.pro:2006/"
priority = "supplemental"

[tool.poetry_extensions.deptry]
ignores = [
    "numpy",
    "pandas",
    "pip",
    "pipgrip",
    "poetry",
    "pyportable_runtime",
    "windows_toasts",
]

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
