[tool.poetry]
name = "depsland"
version = "0.6.0a1"
description = "The core features of Pyportable Installer."
license = "MIT"
authors = ["Likianta <likianta@foxmail.com>"]
homepage = "https://github.com/likianta/depsland"

[tool.poetry.dependencies]
python = "^3.8"
argsense = "^0.5.2"
conflore = "^0.2.0"
lk-logger = "^5.6.2"
lk-utils = "^2.5.6"
oss2 = "*"
# pyside6 = "*"
pyyaml = "*"
qmlease = "^3.0.3"
rich = "*"
semver = "^3.0.1"

[tool.poetry.scripts]
depsland = 'depsland.__main__:_run_cli'

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
priority = "default"

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
