[tool.poetry]
name = "depsland"
version = "0.6.0a1"
description = "The core features of Pyportable Installer."
license = "MIT"
authors = ["Likianta <likianta@foxmail.com>"]
homepage = "https://github.com/likianta/depsland"

[tool.poetry.dependencies]
python = "^3.8"
argsense = "^0.5.2"
conflore = "^0.2.0"
fake-typing = { url = "http://likianta.pro:2006/fake-typing/fake_typing-0.1.0b4-py3-none-any.whl" }
lk-logger = { url = "http://likianta.pro:2006/lk-logger/lk_logger-5.7.0a9-py3-none-any.whl" }
lk-utils = { url = "http://likianta.pro:2006/lk-utils/lk_utils-2.6.1b0-py3-none-any.whl" }
oss2 = "*"
pip = "*"
poetry = "*"
pyside6 = { version = ">=6.4,<6.5", python = ">=3.8,<3.12" }
pyyaml = "*"
qmlease = "^3.0.3"
qtpy = "*"
rich = "*"
semver = "^3.0.1"
toml = { version = "*", python = "<3.11" }
typing-extensions = { version = "*", python = "<3.11" }

[tool.poetry.group.dev.dependencies]
icnsutil = "*"
lkfmt = { url = "http://likianta.pro:2006/lkfmt/lkfmt-0.3.0a17-py3-none-any.whl" }
pillow = "*"
setuptools = "*"

[tool.poetry.scripts]
depsland = 'depsland.__main__:_run_cli'

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
priority = "default"

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
