[tool.poetry]
name = "depsland"
version = "0.8.1b15"
description = "User oriented dependency management and application distribution tool."
license = "MIT"
authors = ["Likianta <likianta@foxmail.com>"]
homepage = "https://github.com/likianta/depsland"

[tool.poetry.dependencies]
python = "^3.8"
# argsense = "^0.5.8"
argsense = { version = "^0.5.9a0", source = "likianta-host" }
conflore = "^0.2.0"
# lk-logger = "^5.7.6"
lk-logger = { version = "^6.0.0a19", source = "likianta-host" }
# lk-utils = "^2.10.7"
# lk-utils = { version = ">=2.11.0b0,<4.0.0", source = "likianta-host" }
lk-utils = { version = "^3.0.0a2", source = "likianta-host" }
oss2 = "^2.18.3"  # DELETE
pip = "^24.0.0"
pipgrip = "^0.10.13"
poetry = "^1.8.3"
psutil = "^6.0.0"
# pyapp-window = "^2.0.0"
pyapp-window = { version = "^2.1.0a3", source = "likianta-host" }
# pyyaml = "^6.0.0"
rich = "^13.7.0"
semver = "^3.0.2"
streamlit = { version = "^1.38.0", python = "!=3.9.7" }
streamlit-extras = "*"
# streamlit-scrollable-textbox = "*"
# toml = { version = "*", python = "<3.11" }
toml = "*"
# typing-extensions = { version = "*", python = "<3.11" }
windows-toasts = { version = "^1.0.0", platform = "win32" }

[tool.poetry.group.dev.dependencies]
ipython = { version = "^8.22.0", python = ">=3.10,<4.0" }
# nuitka = "^2.3.11"

# --- indirect deps
numpy = { version = "^2.0.0", python = ">=3.9" }  # <- streamlit
pandas = { version = "^2.2.2", python = ">=3.9" }  # <- streamlit

# --- sidework
icnsutil = "*"  # <- sidework/image_converter.py
pillow = "*"  # <- sidework/image_converter.py

# --- demo
pyside6 = { version = ">=6.6.0,<6.7.0", python = ">=3.10,<3.13" }  # <- demo/hello-world-gui
pysimplegui = "*"  # <- demo/hello-world-tkinter
qmlease = { version = ">=3.0.5a10,<3.1.0", source = "likianta-host" }  # <- demo/hello-world-gui

[tool.poetry.scripts]
depsland = 'depsland.__main__:_run_cli'

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "likianta-host"
url = "http://likianta.pro:2131/"
priority = "supplemental"

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"

[tool.poetry-extensions]
ignored_redundant_packages = [
    "pip",
    "pipgrip",
    "poetry",
    "pyportable_runtime",
]
