[project]
name = "depsland"
version = "0.12.0a26"
description = "User oriented dependency management and application distribution tool."
authors = [{ name = "Likianta", email = "likianta@foxmail.com" }]
license = "MIT"
# readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "airmise>=3.0.0",
    "argsense>=1.1.2",
    "conflore>=0.2.2",
    "lk-utils>=3.7.0a6",
    "neoprint>=0.1.7a0",
    "oss2>=2.19.1",
    # "pip>=26.0.0",
    # "poetry>=2.3.2",
    "psutil>=7.2.2",
    "pyportable-crypto>=1.6.1a1",
    "semver>=3.0.4",
    "streamlit>=1.58.0",
    "streamlit-canary>=0.3.0b6",
    "streamlit-extras>=1.4.1",
    "streamlit-tree-select>=0.0.5",  # DELETE
    "tree-shaking>=0.2.7a0",
    "windows-toasts>=1.0.0; sys_platform == 'win32'",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling>=1.29.0"]

[dependency-groups]
dev = [
    "freesimplegui>=5.2.0post1",
    "icnsutil>=1.1.0",
    "ipython>=9.15.0",
    "nuitka>=4.1.3",
    "pillow>=12.2.0",
    # "pinkrain>=0.0.0a32",
    # "poetry>=2.3.2",
    "py7zr>=1.1.0",
    "pyapp-window>=2.2.3a0",
    # "pyinstaller>=6.15.0",
    "pyinstrument>=5.1.2",
    # "qmlease[ui]>=4.0.0a6",
    # "reflex>=0.9.3",
    "zstandard>=0.25.0",
]

# [project.optional-dependencies]
# ...

[project.scripts]
depsland = 'depsland.__main__:_cli_entrance'

# [project.urls]
# homepage = "https://github.com/likianta/depsland"

[tool.hatch.build.targets.wheel]
packages = ["depsland"]

[tool.lk.pyproject-manager]
ignore-unused-packages = [
    "ipython",
    "pyapp-window",
    "pyportable-runtime",
]

[tool.ruff]
line-length = 80

[tool.ruff.format]
quote-style = "single"
skip-magic-trailing-comma = true

[tool.ruff.lint]
# extend-select = ["E501"]
# extend-select = ["I001", "E501"]
ignore = ["E701"]

[tool.ruff.lint.isort]
force-single-line = true
relative-imports-order = "closest-to-furthest"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.ruff.lint.pycodestyle]
max-line-length = 83

[tool.ty.environment]
extra-paths = ["./lib"]

[tool.ty.rules]
invalid-type-form = "ignore"
unresolved-attribute = "ignore"

[tool.uv]
prerelease = "allow"

[[tool.uv.index]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true

[[tool.uv.index]]
name = "likianta"
url = "http://localhost:2191/"
# explicit = true

[tool.uv.sources]
airmise = { index = "likianta" }
argsense = { index = "likianta" }
lk-utils = { index = "likianta" }
neoprint = { index = "likianta" }
pinkrain = { index = "likianta" }
pyapp-window = { index = "likianta" }
pyportable-crypto = { index = "likianta" }
qmlease = { index = "likianta" }
streamlit-canary = { index = "likianta" }
tree-shaking = { index = "likianta" }
