[tool.poetry]
name = "depsland"
version = "0.7.0a5"
description = ""
license = "MIT"
authors = ["Likianta <likianta@foxmail.com>"]
homepage = "https://github.com/likianta/depsland"

# po export -o requirements.lock --without-hashes
# python/python.exe -m pip install -r requirements.lock --no-deps \
#   --no-warn-script-location --disable-pip-version-check

[tool.poetry.dependencies]
python = "^3.10"
argsense = "^0.5.3"
conflore = "^0.2.0"
lk-logger = "^5.6.3"
lk-utils = "^2.7.0"
oss2 = "^2.18.3"
pip = "^23.0.0"
poetry = "^1.7.0"
pyyaml = "^6.0.0"
qmlease = "^3.0.3"
rich = "^13.7.0"
semver = "^3.0.2"
typing-extensions = { version = "*", python = "<3.11" }
windows-toasts = { version = "^1.0.0", platform = "win32" }

[tool.poetry.group.dev.dependencies]
pyside6 = [
    { version = ">=6.4.3,<6.5.0", python = ">=3.8,<3.12" },
    { version = "^6.6.1", python = "==3.12" },
]

[tool.poetry.scripts]
depsland = 'depsland.__main__:_run_cli'

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
priority = "default"

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
