[tool.poetry]
name = "depsland"
version = "0.9.0a14"
description = "User oriented dependency management and application distribution tool."
license = "MIT"
authors = ["Likianta <likianta@foxmail.com>"]
homepage = "https://github.com/likianta/depsland"

[tool.poetry.dependencies]
python = "^3.8"
# argsense = "^0.5.8"
argsense = { version = "^0.6.4b1", source = "likianta-host" }
conflore = "^0.2.0"
lk-logger = "^6.0.3"
# lk-logger = { version = "^6.0.2", source = "likianta-host" }
# lk-utils = "^3.1.1"
lk-utils = { version = "^3.1.3a2", source = "likianta-host" }
oss2 = "^2.18.3"
pip = "^24.0.0"
pipgrip = "^0.10.13"  # DELETE?
poetry = "^1.8.5"
psutil = "^6.0.0"
# pyapp-window = "^2.1.1"
pyapp-window = { version = "^2.2.0a11", source = "likianta-host" }
# pyyaml = "^6.0.0"
rich = "^13.8.0"
semver = "^3.0.2"
streamlit = { version = "^1.40.0", python = "!=3.9.7" }
streamlit-extras = "^0.5.0"
streamlit-nested-layout = { version = "^0.1.4", python = "!=3.9.7" }
# toml = { version = "^0.10.0", python = "<3.11" }
toml = "^0.10.0"
windows-toasts = { version = "^1.0.0", platform = "win32" }

[tool.poetry.group.dev.dependencies]
ipython = { version = "^8.31.0", python = "^3.12" }
# nuitka = "^2.3.11"
pinkrain = { version = "^0.0.0a23", source = "likianta-host" }
pyinstaller = { version = "^6.10.0", python = "==3.12" }

# --- demo
pyside6 = { version = ">=6.6.0,<6.7.0", python = ">=3.10,<3.13" }  # <- demo/hello-world-gui
pysimplegui = "^5.0.7"  # <- demo/hello-world-tkinter
qmlease = { version = ">=3.0.5a11,<3.1.0", source = "likianta-host" }  # <- demo/hello-world-gui

# --- experiments
# st-tailwind = { version = "^1.0.5", python = ">=3.9.10,<4.0" }

# --- indirect deps
numpy = { version = "^2.2.0", python = "^3.10" }  # <- streamlit
# pandas = { version = "^2.2.2", python = ">=3.10" }  # <- streamlit
statsmodels = { version = "^0.14.4", python = ">=3.9" }  # <- plotly
toga = { version = "^0.4.8", python = "^3.10" }  # <- pyapp-window

# --- sidework
dash = "^2.17.1"
feffery-antd-components = "^0.3.12"
feffery-dash-utils = "^0.1.4"
icnsutil = "^1.1.0"  # <- sidework/image_converter.py
pillow = { version = "^11.0.0", python = "^3.12" }  # <- sidework/image_converter.py
st-ant-tree = "^0.0.13"
streamlit-canary = { version = "^0.1.0a14", source = "likianta-host" }  # TODO: publish to PyPI, but rename to ...
# streamlit-tree-select = "^0.0.5"

[tool.poetry.scripts]
depsland = 'depsland.__main__:_cli'

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "likianta-host"
url = "http://likianta.pro:2131/"
priority = "supplemental"

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"

[tool.poetry-extensions]
ignored_redundant_packages = [
    "pip",
    "pipgrip",
    "poetry",
    "pyportable_runtime",
]

# ---

[tool.ruff]
line-length = 80
