[tool.poetry]
name = "depsland"
version = "0.3.4b1"
description = ""
license = "MIT"
authors = ["Likianta <likianta@foxmail.com>"]
homepage = "https://github.com/likianta/depsland"
include = ['depsland/chore/*.zip']

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.10"
wheel = "*"
argsense = "^0.4.3"
lk-logger = "^5.4.6"
lk-utils = "~2.5.0"
oss2 = "*"
pyyaml = "*"
rich = "*"
semver = "3.0.0dev3"

gen-exe = { version = "*", markers = "platform_system == 'Windows'" }
pywin32 = { version = "*", markers = "platform_system == 'Windows'" }

[tool.poetry.extras]

[tool.poetry.scripts]
depsland = 'depsland.__main__:_run'

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
