[tool.poetry]
name = "depsland"
version = "0.5.0a1"
description = ""
license = "MIT"
authors = ["Likianta <likianta@foxmail.com>"]
homepage = "https://github.com/likianta/depsland"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.10"
argsense = "^0.5.2"
lk-logger = "^5.4.7"
lk-utils = ">=2.5.2,<2.6.0"
oss2 = "*"
pyside6-essentials = "*"
pyyaml = "*"
qmlease = "*"
rich = "*"
semver = "3.0.0dev3"

[tool.poetry.extras]

[tool.poetry.scripts]
depsland = 'depsland.__main__:_run_cli'

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
