import os
import re
import shlex
import typing as tp
from functools import cache

import pyportable_crypto
from lk_utils import fs

from .assets import index_assets
from .typing import T
from .. import normalization as norm
from ..depsolver import get_tree_shaking_cache_file
from ..depsolver import minify_dependencies
from ..depsolver import resolve_dependencies
from ..utils import hash_text
from ..utils import init_target_tree


def init_manifest(appid: str, appname: str) -> T.ManifestObject:
    return Manifest.init(appid, appname)


def load_manifest(
    file: T.AnyPath, start_directory: T.AnyPath = ''
) -> T.ManifestObject:
    return Manifest.load_from_file(file, start_directory)


def dump_manifest(manifest: T.ManifestObject, file: T.AnyPath) -> None:
    assert isinstance(manifest, Manifest)
    manifest.dump_to_file(file)


def diff_manifest(new: T.Manifest, old: T.Manifest) -> T.ManifestDiff:
    return {
        'assets': _diff_assets(
            new.model['assets'], old.model['assets'], new['assets_redirection']
        ),
        'dependencies': _diff_dependencies(
            new['dependencies'], old['dependencies']
        ),
    }


# ------------------------------------------------------------------------------


class Manifest:
    """
    doc: @wiki/src/developer/manifest-path-format.md
    """

    _file: T.AbsPath
    _manifest: T.Manifest1

    @classmethod
    def init(cls, appid: str, appname: str) -> 'Manifest':
        from .. import __version__

        self = Manifest()
        self._file = ''
        self._manifest = {
            'appid': appid,
            'name': appname,
            'version': '0.0.0',
            'start_directory': '',
            'readme': {'file': '', 'name': '', 'icon': '', 'standalone': True},
            'assets': {},
            'assets_redirection': {},
            'encryption': None,
            'dependencies': {},
            'launcher': {
                'command': '',
                'icon': '',
                'show_console': True,
                'enable_cli': False,
                'add_to_desktop': True,
                'add_to_start_menu': False,
            },
            'experiments': {'package_provider': 'pypi'},
            'depsland_version': __version__,
        }
        return self

    @classmethod
    @cache
    def load_from_file(
        cls, file: T.AnyPath, start_directory: T.AnyPath = ''
    ) -> 'Manifest':
        """
        args:
            file: support '.json', '.yaml'/'.yml', '.pkl' formats.
                the pickle format was generated by depsland itself, and trusted
                by depsland. loading pickle file is faster (since it skips many
                check steps) and more stable (reproducible).
        """
        from .. import __version__

        self = Manifest()
        self._file = fs.abspath(file)
        cfg_dir = fs.parent(self._file)  # abspath

        data0: tp.Union[T.Manifest0, T.Manifest1]
        data1: T.Manifest1

        if self._file.endswith('.pkl'):
            data0: T.Manifest1 = fs.load(self._file)
            data1 = data0
            data1['start_directory'] = start_directory or cfg_dir
        else:
            data0: T.Manifest0
            if self._file.endswith(('.json', '.yaml')):
                data0 = fs.load(self._file)
            elif fs.basename(self._file) == 'pyproject.toml':
                data0 = fs.load(self._file)['tool']['depsland']['manifest']
            elif self._file.endswith('.toml'):
                try:
                    data0 = fs.load(self._file)['tool']['depsland']['manifest']
                except KeyError:
                    data0 = fs.load(self._file)
            else:
                raise Exception('unsupported manifest file format', self._file)

            if not start_directory:
                if 'start_directory' in data0:
                    x = data0['start_directory']
                    if x.startswith('.'):
                        start_directory = fs.normpath(
                            '{}/{}'.format(cfg_dir, x)
                        )
                    else:
                        start_directory = fs.abspath(x)
                else:
                    start_directory = cfg_dir
            print(start_directory, ':v2n')

            if data0.get('readme'):
                if isinstance((x := data0['readme']), str):
                    data0['assets'].append(x)
                elif x := data0['readme']['file']:
                    data0['assets'].append(x)
            if x := data0['launcher'].get('icon'):
                data0['assets'].append(x)
            if data0.get('dependencies'):
                # FIXME: not recommended
                def deduce_entry() -> T.RelPath:
                    if isinstance(data0['launcher']['command'], str):
                        x = shlex.split(data0['launcher']['command'])[1]
                    else:
                        x = data0['launcher']['command'][1]
                    assert x.endswith('.py')
                    return x

                if isinstance(data0['dependencies'], str):
                    if data0['dependencies'] == 'tree_shaking':
                        data0['dependencies'] = {
                            'method': 'tree_shaking',
                            'options': {'entries': [deduce_entry()]},
                        }
                elif data0['dependencies']['method'] == 'tree_shaking':
                    if 'options' in data0['dependencies']:
                        if 'entries' not in data0['dependencies']['options']:
                            data0['dependencies']['options']['entries'] = [
                                deduce_entry()
                            ]
                    else:
                        data0['dependencies']['options'] = {
                            'entries': [deduce_entry()]
                        }

            self._pre_process_manifest(data0, start_directory)
            data1 = {
                'appid': data0['appid'],
                'name': data0['name'],
                'version': self._update_version(
                    data0['version'], start_directory
                ),
                'start_directory': start_directory,
                'readme': self._update_readme_file(
                    data0.get('readme', None), start_directory
                ),
                'assets': self._update_assets(data0['assets'], start_directory),
                'assets_redirection': {},
                'encryption': (
                    self._update_encryption(
                        data0['encryption'], data0['appid'], start_directory
                    )
                    if data0.get('encryption')
                    else None
                ),
                'dependencies': self._update_dependencies(
                    data0.get('dependencies'), start_directory
                ),
                'launcher': self._update_launcher(
                    data0['launcher'], start_directory
                ),
                'experiments': data0.get(
                    'experiments', {'package_provider': 'pypi'}
                ),
                'depsland_version': data0.get('depsland_version', __version__),
            }
            self._post_process_manifest(
                data1, origin_dependency_setting=data0.get('dependencies')
            )

        self._manifest = data1
        return self

    def dump_to_file(self, file: T.AnyPath = '') -> None:
        if not file:
            file = self._file
        if fs.basename(file) == 'pyproject.toml':
            # TODO: how to reserve original comments?
            raise NotImplementedError(file)

        data1: T.Manifest1 = self._manifest
        data0: T.Manifest0 = self._manifest.copy()  # type: ignore

        # modify `data0` fields
        # be noticed some of `data0.values()` are list or dict types, which -
        # should be deep copied if we want to modify their inner items, to -
        # avoid affecting the original data of `data1`.
        data0.pop('start_directory')
        if not file.endswith('.pkl'):
            data0['assets'] = self._plainify_assets(data1['assets'])
            if file.endswith('.toml'):
                data0 = {
                    'tool': {'depsland': {'manifest': data0}}  # type: ignore
                }

        fs.dump(data0, file)

    def make_tree(self, root: str = '') -> None:
        if not root:
            root = self._manifest['start_directory']
        relpaths = []
        for k, v in self._manifest['assets'].items():
            if v.type == 'dir':
                relpaths.append(k)
            else:
                if '/' in k:
                    relpaths.append(k.rsplit('/', 1)[0])
        init_target_tree(root, relpaths)

    # --------------------------------------------------------------------------
    # dict-like behavior

    @property
    def model(self) -> T.Manifest1:
        return self._manifest

    def get(self, key: str) -> tp.Any:
        if key in self._manifest:
            return self[key]
        return None

    def __iter__(self) -> tp.Iterator[tp.Tuple[str, tp.Any]]:
        yield from self._manifest.items()

    def __getitem__(self, key: str) -> tp.Any:
        if key == 'readme':

            class ReadmeGetter:
                def __init__(
                    self, data: T.Readme1, start_directory: T.StartDirectory
                ) -> None:
                    self._data = data
                    self._start_directory = start_directory

                def __bool__(self) -> bool:
                    return bool(self._data['file'])

                def __iter__(self) -> tp.Iterator[tp.Tuple[str, tp.Any]]:
                    yield from self._data.items()

                def __getitem__(self, key: str) -> tp.Union[str, bool]:
                    if key == 'file' or key == 'icon':
                        if x := self._data[key]:  # type: ignore
                            return '{}/{}'.format(self._start_directory, x)
                        else:
                            return ''
                    else:
                        return self._data[key]  # type: ignore

                def __setitem__(self, key: str, value: tp.Any) -> None:
                    raise Exception('cannot modify readme dict', key, value)

            return ReadmeGetter(
                self._manifest['readme'], self._manifest['start_directory']
            )

        elif key == 'encryption':

            class EncryptionGetter:
                def __init__(
                    self, data: T.Encryption1, start_directory: T.StartDirectory
                ):
                    self._data = data
                    self._start_directory = start_directory

                def __getitem__(
                    self, key: tp.Literal['key', 'packages', 'output']
                ) -> tp.Any:
                    if key == 'output':
                        return '{}/{}'.format(
                            self._start_directory, self._data[key]
                        )
                    elif key == 'packages':
                        return tuple(
                            '{}/{}'.format(self._start_directory, x)
                            for x in self._data[key]
                        )
                    else:
                        return self._data[key]

            return (
                EncryptionGetter(
                    self._manifest['encryption'],
                    self._manifest['start_directory'],
                )
                if self._manifest['encryption']
                else None
            )

        elif key == 'launcher':

            class LauncherGetter:
                def __init__(
                    self, data: T.Launcher1, start_directory: T.StartDirectory
                ) -> None:
                    self._data = data
                    self._start_directory = start_directory

                def __iter__(self) -> tp.Iterator[tp.Tuple[str, tp.Any]]:
                    yield from self._data.items()

                def __getitem__(self, key: str) -> tp.Union[str, bool]:
                    if key == 'icon':
                        if x := self._data['icon']:
                            return '{}/{}'.format(self._start_directory, x)
                        else:
                            return ''
                    else:
                        return self._data[key]  # type: ignore

                def __setitem__(self, key: str, value: tp.Any) -> None:
                    raise Exception('cannot modify launcher dict', key, value)

            return LauncherGetter(
                self._manifest['launcher'], self._manifest['start_directory']
            )

        else:
            return self._manifest[key]  # type: ignore

    def __setitem__(self, key: str, value: tp.Any) -> None:
        if key == 'start_directory':
            assert os.path.isabs(value)
            self._manifest[key] = value  # type: ignore
        else:
            raise Exception('cannot modify top field of manifest!', key, value)

    # --------------------------------------------------------------------------

    @staticmethod
    def _pre_process_manifest(
        manifest: T.Manifest0, start_directory: T.StartDirectory
    ) -> None:
        # assert required keys
        required_keys = ('appid', 'name', 'version', 'assets', 'launcher')
        assert all(x in manifest for x in required_keys), (
            'missing required keys',
            'required: {}'.format(required_keys),
            'found: {}'.format(tuple(manifest.keys())),
        )

        assert norm.check_name_normalized(manifest['appid']), (
            'the appid should be lowercase and only contain alphanumber and '
            'underscore.'
        )

        if manifest['version'][0] == '$':
            assert manifest['version'] == '$pyproject_version'
            assert fs.exist('{}/pyproject.toml'.format(start_directory)), (
                'when you configured version to "$pyproject_version", you '
                'should have a "pyproject.toml" file in your project root.'
            )
        else:
            assert re.fullmatch(
                r'\d+\.\d+\.\d+([ab]\d+)?', manifest['version']
            ), manifest['version']

        if manifest.get('readme'):
            assert manifest['readme']
            if isinstance(manifest['readme'], str):
                readme = manifest['readme']
            else:
                if name := manifest['readme'].get('name'):
                    if name.endswith(
                        (
                            '.doc',
                            '.docx',
                            '.htm',
                            '.html',
                            '.md',
                            '.mhtml',
                            '.mp4',
                            '.pdf',
                            '.rst',
                            '.txt',
                            '.wps',
                        )
                    ):
                        raise Exception(
                            'do not include extension in the `readme:name` '
                            'field',
                            manifest['readme']['name'],
                        )
                readme = manifest['readme']['file']
            if readme:
                assert '.' in fs.filename(readme), (
                    'there should be a file extension in your readme file name.'
                    # otherwise it maybe a directory or, we cannot make a proper
                    # name for it in installation stage.
                )

        assert manifest['assets'], 'field `assets` cannot be empty!'
        assert isinstance(manifest['assets'], list)
        assert all(not x.startswith('../') for x in manifest['assets']), (
            'manifest should be put at the root of project, and there shall be '
            'no "../" in your assets keys.'
        )

        if enc := manifest.get('encryption'):
            if not any(enc.values()):
                manifest['encryption'] = None
            else:
                assert enc['key'] and enc['packages'], enc
                assert all(x in manifest['assets'] for x in enc['packages'])
                assert all(
                    fs.exist('{}/{}'.format(start_directory, x))
                    for x in enc['packages']
                )
                if enc['output']:
                    if not fs.exist(
                        '{}/{}'.format(start_directory, enc['output'])
                    ):
                        fs.make_dir(
                            '{}/{}'.format(start_directory, enc['output'])
                        )
                else:
                    enc['output'] = '.depsland/encrypted_packages'
                    fs.make_dirs('{}/{}'.format(start_directory, enc['output']))

        if manifest.get('dependencies'):
            if isinstance(manifest['dependencies'], str):
                if manifest['dependencies'] in ('poetry.lock', 'uv.lock'):
                    print(
                        'remove ".lock" from dependency setting '
                        '({} -> {})'.format(
                            manifest['dependencies'],
                            manifest['dependencies'][:-5],
                        ),
                        ':v6',
                    )
                    manifest['dependencies'] = manifest['dependencies'][:-5]
                else:
                    assert manifest['dependencies'] in ('poetry', 'uv')
            else:  # dict
                assert isinstance(manifest['dependencies'], dict)
                deps_dict = manifest['dependencies']

                assert deps_dict['method'] == 'tree_shaking', deps_dict

                if 'base' in deps_dict:
                    assert deps_dict['base'] in ('poetry.lock', 'uv.lock')
                else:
                    deps_dict['base'] = 'uv.lock'

                assert 'options' in deps_dict
                options = deps_dict['options']

                assert 'root' not in options, (
                    '"root" field in tree-shaking options is managed by '
                    'depsland, do not set it manually.'
                )
                options['root'] = '..'

                if 'export' in options:
                    assert (
                        options['export']['source']
                        and options['export']['target']
                    )
                else:
                    options['export'] = {
                        'source': '.depsland/orig_deps',
                        'target': '.depsland/mini_deps',
                    }

                assert options['entries']

                if 'search_paths' in options:
                    if '.depsland/orig_deps' not in options['search_paths']:
                        options['search_paths'].insert(0, '.depsland/orig_deps')
                else:
                    options['search_paths'] = ['.depsland/orig_deps', '.']

        launcher: T.Launcher0 = manifest['launcher']
        assert launcher['command'], 'field `launcher.command` cannot be empty!'
        if '<python>' in launcher['command']:
            # print(':v6', '"<python>" is deprecate to use, use just "python"')
            # if isinstance(launcher['command'], str):
            #     launcher['command'] = \
            #         launcher['command'].replace('<python>', 'python')
            # else:
            #     assert launcher['command'][0] == '<python>'
            #     launcher['command'][0] = 'python'
            raise Exception(
                '"<python>" is deprecate to use, use just "python" in your '
                'launcher command.'
            )

    def _post_process_manifest(
        self, manifest: T.Manifest1, origin_dependency_setting: T.Dependencies0
    ) -> None:
        # inflate assets from tree_shaking cache
        if (
            origin_dependency_setting
            and isinstance(origin_dependency_setting, dict)
            and origin_dependency_setting['method'] == 'tree_shaking'
        ):
            mini_deps_cache_file = get_tree_shaking_cache_file(
                manifest['start_directory'], origin_dependency_setting['base']
            )
            print('inflate assets from ".depsland/mini_deps/*"')
            manifest['assets'].update(fs.load(mini_deps_cache_file))

        # update assets redirection
        if enc := manifest['encryption']:
            print(
                'redirect part of assets to encrypted ones',
                enc['packages'],
                ':ln',
            )
            manifest['assets_redirection'].update(
                {
                    k: '{}/{}'.format(enc['output'], fs.barename(k))
                    for k in enc['packages']
                }
            )
            manifest['assets'].update(
                self._update_assets(
                    ['{}/pyportable_runtime'.format(enc['output'])],
                    manifest['start_directory'],
                )
            )

        if x := manifest['launcher']['icon']:
            assert x.endswith('.ico'), (
                'make sure the icon file is ".ico" format. if you have other '
                'file type, please use a online converter (for example '
                'https://findicons.com/convert) to get one.'
            )
            # TODO: check icon size and give suggestions (the size is -
            #   suggested 128x128 or higher.)
        if manifest['launcher']['add_to_start_menu']:
            print(
                ':v6',
                '`launcher:add_to_start_menu` is not tested yet. this is an '
                'experimental feature.',
            )

    # --------------------------------------------------------------------------

    def _update_assets(
        self, assets0: T.Assets0, start_directory: T.StartDirectory
    ) -> T.Assets1:
        return index_assets(assets0, start_directory)

    def _update_dependencies(
        self, deps0: T.Dependencies0, start_directory: T.StartDirectory
    ) -> T.Dependencies1:
        if not deps0:  # None, empty dict, empty str.
            return {}
        elif isinstance(deps0, str):
            if deps0 == 'uv':
                return resolve_dependencies('uv.lock', start_directory)
            else:  # 'poetry'
                return resolve_dependencies('poetry.lock', start_directory)
        else:  # dict
            minify_dependencies(
                start_directory,
                deps0['options']['entries'],
                deps0['options']['search_paths'],
                deps0['options']['export'],
                deps0['base'],
            )
            return {}

    def _update_encryption(
        self,
        options: T.Encryption0,
        appid: str,
        start_directory: T.StartDirectory,
    ) -> T.Encryption1:
        assert options

        from ..cache import get_project_cache
        from ..cache import is_project_cached
        from ..cache import save_project_cache

        def determine_encryption_key() -> str:
            key0 = options['key']
            if key0 == '$env':
                key1 = os.environ['DEPSLAND_APP_SECRET_KEY']
            elif key0.startswith('$env:'):
                key1 = os.environ[key0[5:]]
            else:
                key1 = key0
            if options.get('add_salt'):
                key1 = pyportable_crypto.keygen.add_salt(key1)
            if key1 != key0:
                print(
                    'resolved encryption key: {} -> {}'.format(key0, key1),
                    ':r2',
                )
            return key1

        def check_if_reusable() -> bool:
            if not fs.exist(
                _abspath('{}/pyportable_runtime'.format(options['output']))
            ):
                return False
            if not is_project_cached(appid):
                return False
            proj_cache = get_project_cache(appid, options, start_directory)
            enc_cache = proj_cache['encryption']
            assert enc_cache
            if enc_cache['key_hash'] != hash_text(options['key']):
                return False
            if enc_cache['output'] != options['output']:
                return False
            for k0, v0 in enc_cache['packages'].items():
                if k0 not in options['packages']:
                    return False
                if v0 != fs.mtime(
                    '{}/{}'.format(start_directory, k0), recursive=True
                ):
                    return False
            return True

        def encrypt_source() -> None:
            fs.copy_tree(
                pyportable_crypto.generate_cipher_package(options['key']),
                _abspath('{}/pyportable_runtime'.format(options['output'])),
                True,
            )
            for pkg_relpath in options['packages']:
                pyportable_crypto.compile_package(
                    dir_i=_abspath(pkg_relpath),
                    dir_o=_abspath(
                        '{}/{}'.format(
                            options['output'], fs.barename(pkg_relpath)
                        )
                    ),
                    key=options['key'],
                    add_runtime_package='none',
                )

        def save_changes() -> None:
            save_project_cache(appid, options, start_directory)

        def _abspath(relpath: T.RelPath) -> T.AbsPath:
            return '{}/{}'.format(start_directory, relpath)

        options['key'] = determine_encryption_key()
        if check_if_reusable():
            print('reuse encrypted resources from last time', ':v3')
        else:
            encrypt_source()
            save_changes()
        return options

    def _update_launcher(
        self, launcher0: T.Launcher0, start_directory: T.StartDirectory
    ) -> T.Launcher1:
        out: T.Launcher1 = {
            'command': '',
            'icon': '',
            'show_console': True,
            'enable_cli': False,
            'add_to_desktop': False,
            'add_to_start_menu': False,
        }

        if isinstance(launcher0['command'], str):
            out['command'] = launcher0['command']
        else:
            out['command'] = shlex.join(launcher0['command'])

        if launcher0.get('icon'):
            out['icon'] = self._make_relpath(launcher0['icon'], start_directory)
            # print(out['icon'], ':v')

        for k in (
            'show_console',
            'enable_cli',
            'add_to_desktop',
            'add_to_start_menu',
        ):
            if k in launcher0:
                assert isinstance((v := launcher0[k]), bool)
                out[k] = v

        return out

    def _update_readme_file(
        self, readme: tp.Optional[T.Readme0], start_directory: T.StartDirectory
    ) -> T.Readme1:
        out: T.Readme1 = {
            'file': '',
            'name': '',
            'icon': '',
            'standalone': True,
        }
        if readme:
            if isinstance(readme, str):
                out['file'] = self._make_relpath(readme, start_directory)
                out['name'] = fs.barename(out['file'])
            else:
                if readme['file']:
                    out['file'] = self._make_relpath(
                        readme['file'], start_directory
                    )
                    out['name'] = readme.get('name', fs.barename(out['file']))
                    out['standalone'] = readme.get('standalone', True)
                    if readme.get('icon'):
                        out['icon'] = self._make_relpath(
                            readme['icon'], start_directory
                        )
        return out

    def _update_version(
        self, version: str, start_directory: T.StartDirectory
    ) -> str:
        if version == '$pyproject_version':
            return fs.load('{}/pyproject.toml'.format(start_directory))[
                'project'
            ]['version']
        return version

    # --------------------------------------------------------------------------

    @staticmethod
    def _make_relpath(path: T.AnyPath, base: T.AbsPath) -> T.RelPath:
        if os.path.isabs(path):
            assert fs.normpath(path).startswith(base + '/')
            return fs.relpath(path, base)
        else:
            return fs.normpath(path)

    @staticmethod
    def _plainify_assets(assets1: T.Assets1) -> T.Assets0:
        out = []
        for path, info in assets1.items():
            if info.scheme is not None:
                path += ':{:02b}'.format(info.scheme)
            out.append(path)
        return out


# ------------------------------------------------------------------------------


def _diff_assets(
    new: T.Assets1,
    old: T.Assets1,
    redirection_map: tp.Optional[T.AssetsRedirection] = None,
) -> T.AssetsDiff:
    """
    ref: wiki/src/devnote/assets-diff-strategy.md
    """
    if not redirection_map:
        redirection_map = {}

    def is_same(new: T.AssetInfo, old: T.AssetInfo) -> bool:
        """
        comparing assets is considered based on a variety of factors:
            - scheme
            - type
            - hash
            - utime
        """
        if new.scheme == old.scheme == 0b00:
            return True
        if new.scheme != old.scheme:
            return False
        if new.type != old.type:
            return False
        if new.type == 'file' and new.hash == old.hash:
            return True
        if new.utime == old.utime:  # FIXME: used for dir only?
            return True
        if new.type == 'dir' and new.hash == old.hash != '':
            return True
        return False

    for key0, info0 in old.items():
        if key0 not in new:
            assert key0 not in redirection_map
            yield 'delete', (key0, key0), (info0, None)

    for key1, info1 in new.items():
        if key1 not in old:
            yield (
                'append',
                (key1, redirection_map.get(key1, key1)),
                (None, info1),
            )
            continue
        info0 = old[key1]
        if is_same(info1, info0):
            yield (
                'ignore',
                (key1, redirection_map.get(key1, key1)),
                (info0, info1),
            )
        else:
            yield (
                'update',
                (key1, redirection_map.get(key1, key1)),
                (info0, info1),
            )


def _diff_dependencies(new: T.Packages, old: T.Packages) -> T.DependenciesDiff:
    info0: T.PackageInfo
    info1: T.PackageInfo

    for name0, info0 in old.items():
        if name0 not in new:
            yield 'delete', name0, (info0, None)
            continue

        name1, info1 = name0, new[name0]
        if info1['version'] != info0['version']:
            yield 'update', name1, (info0, info1)
        else:
            yield 'ignore', name0, (info0, info1)

    for name1, info1 in new.items():
        if name1 not in old:
            yield 'append', name1, (None, info1)
